### ISSUE TITLE
X64 not working on windows 11 24H2

### ISSUE THREAD

**Issue by idigger** [hellokittyfan48/process-hollowing#2]
![er2222222222222](https://github.com/user-attachments/assets/f9d552d1-262a-4000-b3c6-c18c256f661e)

It's ok on before windows 11 24H2

X86 running ok.
![oklllllllllllllll](https://github.com/user-attachments/assets/7c320aa6-7210-4aab-8dc4-cef4e0479e29)

**Comment by hellokittyfan48** [comment]
The folder SysWOW64 is a compatibility subsystem that enables 64-bit versions of Windows to run 32-bit applications, what you are running is the x86 version of svchost.exe, the default directory for x64 system files is System32 inside the Windows folder on your boot drive.
